apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: production-public-ips
spec:
  loadBalancerIP: 192.168.99.100
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: ftp-cmd
      port: 21
      targetPort: 21
    - name: ftp-data
      port: 20
      targetPort: 20
    - name: pasv-1
      protocol: TCP
      port: 22000
      targetPort: 22000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 22000