apiVersion: v1
kind: Service
metadata:
  name: influx-svc
spec:
  selector:
    app: influx
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influx_data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deployment
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      volumes:
      - name: influx-pv-volume
        persistentVolumeClaim:
          claimName: influx-pv-claim
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      containers:
      - name: influx
        image: influx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: "var/lib/influxdb"
          name: influx-pv-volume
        - mountPath: "var/run/docker.sock"
          name: docker-sock