apiVersion: v1
kind: Service
metadata:
  name: php-my-admin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: production-public-ips
spec:
  loadBalancerIP: 192.168.99.100
  selector:
    app: php-my-admin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-my-admin-deployment
  labels:
    app: php-my-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-my-admin
  template:
    metadata:
      labels:
        app: php-my-admin
    spec:
      containers:
      - name: php-my-admin
        image: php_my_admin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000