apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: production-public-ips
spec:
  loadBalancerIP: 192.168.99.100
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443